import { Film } from './types';

export const FILMS: Film[] = [
  {
    id: 1,
    title: "Lost in Translation",
    year: "2003",
    director: "Sofia Coppola",
    stillUrl: "https://picsum.photos/seed/lostintranslation/800/1200",
    verdict: "Bugün yoruldun. Sana sessizce ağlatan bir şey gerekiyor.",
    valence: 'negative',
    arousal: 'slow',
    world: 'mirror',
    synopsis: "Japonya'da geçen hüzünlü ve güzel bir hikaye.",
    rating: 7.7,
    cast: ["Bill Murray", "Scarlett Johansson"]
  },
  {
    id: 2,
    title: "Paterson",
    year: "2016",
    director: "Jim Jarmusch",
    stillUrl: "https://picsum.photos/seed/paterson/800/1200",
    verdict: "Bugün yoruldun. Sana sessizce ağlatan bir şey gerekiyor.",
    valence: 'negative',
    arousal: 'slow',
    world: 'mirror',
    synopsis: "Bir otobüs şoförünün sıradan ama şiirsel hayatı.",
    rating: 7.4,
    cast: ["Adam Driver", "Golshifteh Farahani"]
  },
  {
    id: 3,
    title: "Manchester by the Sea",
    year: "2016",
    director: "Kenneth Lonergan",
    stillUrl: "https://picsum.photos/seed/manchester/800/1200",
    verdict: "Bugün yoruldun. Sana sessizce ağlatan bir şey gerekiyor.",
    valence: 'negative',
    arousal: 'slow',
    world: 'mirror',
    synopsis: "Geçmişin yükü ve yas üzerine etkileyici bir dram.",
    rating: 7.8,
    cast: ["Casey Affleck", "Michelle Williams"]
  },
  {
    id: 4,
    title: "Prisoners",
    year: "2013",
    director: "Denis Villeneuve",
    stillUrl: "https://picsum.photos/seed/prisoners/800/1200",
    verdict: "İçinde bir gerilim var. Onu bir yere akıtmak istiyorsun.",
    valence: 'negative',
    arousal: 'fast',
    world: 'mirror',
    synopsis: "Kayıp bir çocuk ve adaleti kendi eline alan bir baba.",
    rating: 8.1,
    cast: ["Hugh Jackman", "Jake Gyllenhaal"]
  },
  {
    id: 5,
    title: "Zodiac",
    year: "2007",
    director: "David Fincher",
    stillUrl: "https://picsum.photos/seed/zodiac/800/1200",
    verdict: "İçinde bir gerilim var. Onu bir yere akıtmak istiyorsun.",
    valence: 'negative',
    arousal: 'fast',
    world: 'mirror',
    synopsis: "Bir seri katilin peşindeki saplantılı bir arayış.",
    rating: 7.7,
    cast: ["Jake Gyllenhaal", "Robert Downey Jr."]
  },
  {
    id: 6,
    title: "Spirited Away",
    year: "2001",
    director: "Hayao Miyazaki",
    stillUrl: "https://picsum.photos/seed/spirited/800/1200",
    verdict: "Kaçmak istiyorsun — ama güzelliğe doğru.",
    valence: 'positive',
    arousal: 'slow',
    world: 'escape',
    synopsis: "Büyülü bir dünyada mahsur kalan küçük bir kızın macerası.",
    rating: 8.6,
    cast: ["Daveigh Chase", "Jason Marsden"]
  },
  {
    id: 7,
    title: "Amelie",
    year: "2001",
    director: "Jean-Pierre Jeunet",
    stillUrl: "https://picsum.photos/seed/amelie/800/1200",
    verdict: "Kaçmak istiyorsun — ama güzelliğe doğru.",
    valence: 'positive',
    arousal: 'slow',
    world: 'escape',
    synopsis: "Başkalarının hayatlarını değiştiren utangaç bir garsonun hikayesi.",
    rating: 8.3,
    cast: ["Audrey Tautou", "Mathieu Kassovitz"]
  },
  {
    id: 8,
    title: "Mad Max: Fury Road",
    year: "2015",
    director: "George Miller",
    stillUrl: "https://picsum.photos/seed/madmax/800/1200",
    verdict: "Bu gece sınırları kırmak istiyorsun. Başka bir evren.",
    valence: 'negative',
    arousal: 'fast',
    world: 'escape',
    synopsis: "Adrenalin dolu bir kıyamet sonrası kaçış macerası.",
    rating: 8.1,
    cast: ["Tom Hardy", "Charlize Theron"]
  },
  {
    id: 9,
    title: "Dune",
    year: "2021",
    director: "Denis Villeneuve",
    stillUrl: "https://picsum.photos/seed/dune/800/1200",
    verdict: "Bu gece sınırları kırmak istiyorsun. Başka bir evren.",
    valence: 'negative',
    arousal: 'fast',
    world: 'escape',
    synopsis: "Uzak bir gelecekte bir gezegen uğruna verilen hanedan savaşı.",
    rating: 8.0,
    cast: ["Timothée Chalamet", "Rebecca Ferguson"]
  },
  {
    id: 10,
    title: "Interstellar",
    year: "2014",
    director: "Christopher Nolan",
    stillUrl: "https://picsum.photos/seed/interstellar/800/1200",
    verdict: "Bu gece sınırları kırmak istiyorsun. Başka bir evren.",
    valence: 'negative',
    arousal: 'fast',
    world: 'escape',
    synopsis: "İnsanlığın kurtuluşu için uzayın derinliklerine yolculuk.",
    rating: 8.6,
    cast: ["Matthew McConaughey", "Anne Hathaway"]
  }
];
